    # set(TEST_CONFIGURATION configuration-test)

    # add_executable(${TEST_CONFIGURATION}
    #     configuration_tests/configuration-test.cpp
    #     ${PROJECT_SOURCE_DIR}/implementation/plugin/src/plugin_manager_impl.cpp
    # )
    # target_link_libraries(${TEST_CONFIGURATION}
    #     vsomeip3
    #     vsomeip3-cfg
    #     ${Boost_LIBRARIES}
    #     ${DL_LIBRARY}
    #     ${TEST_LINK_LIBRARIES}
    # )


